### ISSUE TITLE
Scroll containers

### ISSUE THREAD

**Issue by oliviertassinari** [focus-trap/tabbable#167]
An effort among user-agent is underway to make scroll container tabbable. You can find https://github.com/whatwg/html/issues/2851 and https://www.chromestatus.com/feature/5231964663578624 on this topic. On macOS Firefox 83.0, scroll containers are focusable, on Ubuntu 20.04 Chrome 87 too. Is this something you plan to support?

**Comment by idoros** [comment]
Technically this means any element with overflow auto or scroll and scroll size larger then it's size is tabbable. 

I agree that identifying these elements as tabbable is useful, however I suggest that this will not be supported by default since the spec issue is closed stating that it's up to the UA to decide how this works and I'm not sure if there is an efficient way to do this.

Maybe Tabbable can offer a flag to run this additional search and allow the developer to decide when to run it.

**Comment by stefcameron** [comment]
@oliviertassinari Thanks for bringing attention to this. I read through the two links you provided, and links from there. Based on https://github.com/whatwg/html/issues/2851#issuecomment-534419269, however, it sounds like this has ended-up in the realm of "browser choice", which means we'd need various levels of browser detection, keeping in sync with changing behaviors on browsers (e.g. some browsers don't have support, some do and that could change, etc.), and also trying to find non-performance-intensive ways to detect "scrollers", as they call them. #115 tells me that our users care a great deal about performance, here and in `focus-trap`, and I'm not aware of efficient web APIs to detect these scrollers.

So with all that considered, I feel like it's not worth the effort to attempt to implement -- and maintain -- support for this.

A workaround, albeit perhaps not as elegant as on-the-fly detection by `tabbable`, would be to set `tabindex=0` on those containers which may end-up being scrollable in certain circumstances. Worse case scenario, uses have to tab through an element that isn't scrollable if they have, what, a large-enough monitor, and at best, it's scrollable and they always get to stop there with focus and scroll it as needed.

**Comment by oliviertassinari** [comment]
@stefcameron Thanks for the update, we took a similar tradeoff in https://github.com/mui-org/material-ui/pull/23364.
