### ISSUE TITLE
isTabbableRadio doesn't properly escape query selectors

### ISSUE THREAD

**Issue by tidychips** [focus-trap/tabbable#168]
It's possible for radio button names to contain characters that are invalid when used in a CSS selector (e.g. `"`).  Below is an example that causes the `tabbable` function to throw an error due to an invalid selector constructed at: <https://github.com/focus-trap/tabbable/blob/cd06b988e9b1924405ba406c1a503046af2687a2/src/index.js#L105>

**HTML:**
```html
<div>
  <input type="radio" id="huey" name="&quot;duck&quot;" value="huey"
         checked>
  <label for="huey">Huey</label>
</div>

<div>
  <input type="radio" id="dewey" name="&quot;duck&quot;" value="dewey">
  <label for="dewey">Dewey</label>
</div>
```

**JS:**
```js
import { tabbable } from 'tabbable';
// Throws DOMException: Document.querySelectorAll: 'input[type="radio"][name=""duck""]' is not a valid selector
tabbable(document.body);
```

It's also possible to inject values into the selector with a name like:

```html
<input type="radio" id="dewey" name="&quot;] .some-class[data-attr=&quot;some-attribute" value="dewey">
```

A potential solution is [CSS.escape](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape), but it does require a polyfill for IE.

**Comment by idoros** [comment]
I'm for adding `CSS.escape` around the radio element name,

However I wouldn't add the polyfill, maybe just write about it in the docs because 
1. IE being almost at [end of life](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666).
2. IE as [~1%](https://gs.statcounter.com/browser-market-share#monthly-202011-202011-bar) - [~1.89%](https://netmarketshare.com/browser-market-share.aspx?options=%7B%22filter%22%3A%7B%7D%2C%22dateLabel%22%3A%22Custom%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22browser%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22browsersDesktop%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222020-11%22%2C%22dateEnd%22%3A%222020-11%22%2C%22segments%22%3A%22-1000%22%7D) market share at this point
3. this is not a very common name (I get that it might be used by some automated system)

I'm not sure injection could cause any serious trouble here, the process that the query is being used in just checks if a radio element is not tabbable: (1) get a list of candidates elements that are supposed to be in the tested radio group **(here you might cause different elements to be selected)** (2) if one of those elements has a positive `.check` property and it's not the tested radio, then the **originally tested radio element** that is not supposed to be tabbable will return as tabbable (notice that it's still a valid focusable element).

**Comment by tidychips** [comment]
Thanks for the suggestion around the polyfill @idoros, I've created PR following it.  I also agree that the ramifications of any injections are fairly trivial.

**Comment by stefcameron** [comment]
@all-contributors add @tidychips for bug
