### ISSUE TITLE
Optimizing displayCheck: 'full'

### ISSUE THREAD

**Issue by DaviDevMod** [focus-trap/tabbable#592]
It is possible to assess whether an element, or one of its ancestors, have `display: none` without having to traverse the DOM.

[This condition](https://github.com/focus-trap/tabbable/blob/7609e9ecf47941a2b69aab2149e8760ea1f7392e/src/index.js#L153) can be simplified to:

```javascript
if (!displayCheck || displayCheck === 'full') {
  return !node.getClientRects().length;
}
```

I actually don't know if checking for `getClientRects().length` is really equivalent to that expensive `while` loop.
 
According to the specs, the [`getClientRects()`](https://drafts.csswg.org/cssom-view/#dom-element-getclientrects) method returns an empty list

> If the element on which it was invoked does not have an associated [layout box](https://drafts.csswg.org/cssom-view/#layout-box)

What exactly are all the cases in which an element does not have an associated layout box? I am not sure.

But the e2e tests currently present in the project are all passing.  
However I didn't go through the tests myself and I don't know what they do, I only checked [this very small set of possible edge cases](https://codesandbox.io/s/great-frog-65yr2y?file=/index.html) and it looks like the method should be good enough.

May I open a PR?

By the way, since the [`getBoundingClientRect()`](https://drafts.csswg.org/cssom-view/#dom-element-getboundingclientrect) method internally uses `getClientRects()`, the `"full"` option would become faster than the `"non-zero-area"` one. But I guess that the latter would still be useful for accessibility purpose.

**Comment by stefcameron** [comment]
> What exactly are all the cases in which an element does not have an associated layout box? I am not sure.

It looks like it's this from [css-layout-box](https://drafts.csswg.org/cssom-view/#css-layout-box):

> The term CSS layout box refers to the same term in CSS. For the purpose of the requirements in this specification, elements that have a computed value of the [display](https://drafts.csswg.org/css-display-3/#propdef-display) property that is [table-column](https://drafts.csswg.org/css-display-3/#valdef-display-table-column) or [table-column-group](https://drafts.csswg.org/css-display-3/#valdef-display-table-column-group) must be considered to have an associated [CSS layout box](https://drafts.csswg.org/cssom-view/#css-layout-box) (the column or column group, respectively).

But somehow that doesn't sound "complete".

> I actually don't know if checking for getClientRects().length is really equivalent to that expensive while loop.

That is the most important question to answer, because I think you're proposing to _replace_ the while loop with a single `node.getClientRects().length <= 0` check, right?

That while loop is the library's tried and true default behavior. Changing this could break _a lot_ of projects out there, so we need a way to be absolutely certain the result would be the same. Tabbable is nearing 1 million [weekly downloads](https://www.npmjs.com/package/tabbable), and I don't want to break near a million projects... 😅 

If we can be certain that `getClientRects()` is functionality equivalent, then I agree, that seems to be a winner because we'd be trading a lot of [layout reflows](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#getting-box-metrics) walking up the tree with a single one.

See #115 for some background on how we got to what we have today.

**Comment by DaviDevMod** [comment]
One million per week, wow. That's an unreasonably huge amount. 

As you noticed, the specs are not very useful when it comes to define what the css-layout-box is, let alone exhaustively elencate the cases in which an element does not have an associated layout box.

Would it be possible to leverage the huge number of users, by providing an alpha (beta or whatever) release that people having layout reflow problems would probably try out? Possibly they would report some issue shading light on the behaviour of `getClientRect()`, or possibly no issue will be found and after a while the method could be considered "safe".

**Comment by DaviDevMod** [comment]
As [MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model) states:

> Everything in CSS has a box around it

Again on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/display-box):

> These keywords define whether an element generates display boxes at all.

So `display: "none"` prevents the element from generating  a display box, which makes `getClientRect()` return a zero-lenghted list.

Now in the comments above, I was wondering if there were ways - other than `display: "none"` - of preventing an element from generating a display box.  
But he fact is that it doesn't matter: if there are no other ways, then checking `getClientRect().length` is equivalent to traversing the DOM in search of a `display: "none"`; if there are other ways, then checking `getClientRect().length` is even better than traversing the DOM since it accounts for other edge cases in which an element should not be focusable.

There was some confusion in the comments above, but I hope that now it's clear enough how `getClientRect` is by all means better than the current while loop.

**Comment by DaviDevMod** [comment]
After reading #115, it looks like `displayCheck` was introduced to improve *tabbable*'s performance.

Since the optimisation proposed in this issue would resolve the need for better performance, without needing a `displayCheck` option, it could be reasonable to remove the option altogether making *tabbable* simpler, again.

I thought I could show some initiative, so I made a branch on my fork where I removed `displayCheck`. [Here it is](https://github.com/DaviDevMod/tabbable/tree/perf/removing-displaycheck).

**Comment by stefcameron** [comment]
> Would it be possible to leverage the huge number of users, by providing an alpha (beta or whatever) release that people having layout reflow problems would probably try out? Possibly they will report some issue shading light on the behaviour of getClientRect(), or possibly no issue will be found and after a while the method could be considered a valid substitute to traversing the DOM.

That's a reasonable suggestion, but we're already running a beta of tabbable (and focus-trap) for Shadow DOM support:

- #570 
- https://github.com/focus-trap/focus-trap/pull/610

It'll be a while still before we could do another alpha or beta with this change in it to test the waters.

> Spoiler: there is at least one more way of preventing an element from generating display boxes, which is display: "contents". This edge case is not handled by the current "full" option, but would be handled automatically in case getClientRect().length gets implemented.

🤨 OK, interesting! But "contents" means the element should display its children instead of itself. So the element itself is kind of "bypassed" as far as display goes, so it doesn't get a display box, but its children will get one. So if the current while loop stopped on "contents", it could be wrong. A child could be displayed, but the parent have `display: contents`, and we'd hit the parent, see that `display` is `'contents' || 'none'` and exit, thinking the child isn't displayed. That would be wrong.

So as long as `getClientRects()` still returns the child's rect, then it should be OK.

And if we're checking `getClientRects()` on a child, but a parent has `display: 'none'`, then I assume the result is also a zero-length array of display rects, hopefully.

> I thought I could show some initiative, so I made a branch on my fork where I removed displayCheck. [Here it is](https://github.com/DaviDevMod/tabbable/tree/perf/removing-displaycheck).

I appreciate the initiative, for sure! I had a look. I was expecting to see just a small (but significant!) change to `isHidden()`, however you have removed the display check options altogether. I'd much prefer not doing that because it'll not only be a breaking change in tabbable, but also all the up the stack through focus-trap and focus-trap-react as well. The only thing we should do here is replace the while loop with `!node.getClientRects().length;`, and add more tests to make sure all those corner cases still work (or work better) with `getClientRects()` as/than they did with the `display === 'none'` while loop.

**Comment by DaviDevMod** [comment]
> So as long as getClientRects() still returns the child's rect, then it should be OK.

> And if we're checking getClientRects() on a child, but a parent has display: 'none', then I assume the result is also a zero-length array of display rects, hopefully.

I updated the [small set of possible edge cases](https://codesandbox.io/s/great-frog-65yr2y?file=/index.html) to include children of `display: "none"` and `display: "contents"`, and everything works as expected.

> The only thing we should do here is replace the while loop with !node.getClientRects().length;, and add more tests to make sure all those corner cases still work (or work better) with getClientRects() as/than they did with the display === 'none' while loop.

That's all right. I understand that removing `displayCheck` would be a big change needing a lot care. Though I hope you'll reconsider this possibility.

Regarding the tests, I have no experience whatsoever with cypress (and e2e testing in general), so I could leave them up to someone else. On the other hand, this would be a nice opportunity to get started with e2e testing, so I can write the tests if you don't mind having to wait for me learning a bit about cypress. But if you do mind, I totally understand and respect that.

**Comment by stefcameron** [comment]
> That's all right. I understand that removing displayCheck would be a big change needing a lot care. Though I hope you'll reconsider this possibility.

I'm up for the change, but I don't want a breaking change. As long as we can be surgical about it, then we're good to go. Even though the other modes will still exist, we're talking about optimizing the default path, which is what probably (guessing) 98% of consumers are using. So many people may see a performance gain. It'll have a big enough impact as it is.

> Regarding the tests, I have no experience whatsoever with cypress (and e2e testing in general), so I could leave them up to someone else. On the other hand, this would be a nice opportunity to get started with e2e testing, so I can write the tests if you don't mind having to wait for me learning a bit about cypress. But if you do mind, I totally understand and respect that.

Go for it! Use it as a learning opportunity. No rush at all. This is an optimization, not a time-sensitive critical bug fix or something like that. 😄

One tip: Cypress does __not__ natively support tabbing. Shocking, I know, but it is what it is. We have to use a plugin to support `.tab()` and this plugin does not support all scenarios. You may run into a scenario where you're bashing your head against a wall thinking you're going nuts because Cypress keeps failing with an error (which is actually from the plugin) complaining that some node you've landed on isn't a tabbable target (or something like that). That's a failure of the plugin, not you, and you'll have to be creative, or we'll have to pass on testing that specific aspect. focus-trap has a few instances of this that I recall, with comments about it, so maybe looking at [focus-trap Cypress tests](https://github.com/focus-trap/focus-trap/blob/master/cypress/integration/focus-trap-demo.spec.js) might help in your work here.

**Comment by DaviDevMod** [comment]
> One tip: Cypress does **not** natively support tabbing. Shocking, I know, but it is what it is. We have to use a plugin to support `.tab()` and this plugin does not support all scenarios.

Thanks for the opportunity and the tip, I'll see what I can do :laughing:

**Comment by craigkovatch** [comment]
> That while loop is the library's tried and true default behavior. Changing this could break _a lot_ of projects out there, so we need a way to be absolutely certain the result would be the same. Tabbable is nearing 1 million [weekly downloads](https://www.npmjs.com/package/tabbable), and I don't want to break near a million projects... 😅
> 
> If we can be certain that `getClientRects()` is functionality equivalent, then I agree, that seems to be a winner because we'd be trading a lot of [layout reflows](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#getting-box-metrics) walking up the tree with a single one.

@stefcameron 🔮😉
https://github.com/focus-trap/tabbable/issues/664
