### ISSUE TITLE
Incorrect README import instructions 

### ISSUE THREAD

**Issue by josephdburdick** [focus-trap/tabbable#90]
In the README it states to import this module you need to use a named import instead of a default import.
```
import { tabbable } from 'tabbable';
```
`tabbable` is undefined.

You my want to update it to reflect the need for a default import.

**Comment by stefcameron** [comment]
Thanks for reaching out! That's kind of strange, because we removed the default export in our 5.0.0 release. You can see [in the code](https://github.com/focus-trap/tabbable/blob/master/src/index.js#L204) that we no longer provide a default export. Also, focus-trap, which consumes this module, [doesn't use a default export either](https://github.com/focus-trap/focus-trap/blob/master/index.js#L1).

What version of the package are you using? If it's `<5.0.0`, then you'll have a default export. Otherwise, it shouldn't be so.

If it's `>=5.0.0`, then what build (CJS, ESM, or UMD) are you using?

**Comment by josephdburdick** [comment]
Thanks for the reply, @stefcameron !
Looks like we're on v4 for the time being but will consider upgrading to v5. 

Thanks!

**Comment by stefcameron** [comment]
😌  My pleasure!
