### ISSUE TITLE
Can't make it work testing with tabbable mocked

### ISSUE THREAD

**Issue by neeco90** [focus-trap/tabbable#943]
Hi guys, sorry for leaving this here but I can't find any solution. I'm trying to mock tabbable to use with jest and I followed the instructions that you leaved but I'm getting an error "TypeError: tabbable.tabbable is not a function" when test runs. 

My root for jest is defined in '<rootDir>/packages/core', so that is why I placed mock folder there. Any ideas where could be the issue?
![image](https://user-images.githubusercontent.com/8958987/224032764-2b8e5aee-3b13-4452-bfe6-85e5698a487b.png)

**Comment by stefcameron** [comment]
@neeco90 Thanks for reaching out! Let's see if we can figure this out.

It looks like you correctly followed the [Testing in JSDom](https://github.com/focus-trap/tabbable#testing-in-jsdom) topic in the README. If you hadn't, it wouldn't lead to this type of error. It would lead to errors like "your container must have at least one tabbable node in it"

This feels more like an issue with CJS `require` vs ESM `import` statements and the fact that Jest doesn't work with ESM. ES modules need to be transpiled to CJS to run under Jest, although tabbable provides both CJS and ESM bundles and, at least in my own projects that use it, doesn't typically have to be configured under Jest's [transformIgnorePatterns](https://stackoverflow.com/a/55803188/6465363) option.

Sill, it _feels_ like something related to this.

Maybe it's in the way you're importing (or requiring?) `tabbable` in your actual code since it seems to occur when you run what I'm guessing is RTL's `render()` function?

**Comment by neeco90** [comment]
Thanks for the quick answer! I'm just using the FocusTrap component in the modal, I'm not importing tabbable in any place. 
![image](https://user-images.githubusercontent.com/8958987/224315288-da107bec-3b7c-4534-8465-b53fd646e04d.png)

I've tried changing the extension to .js but not recognizes jest. I'll keep investigating.

Thanks!

**Comment by neeco90** [comment]
I've find that the unrecognized jest error is just a misconfiguration for eslint, so it passes disabling eslint. But... now throws "unexpected token export" and can't get where is the error
![image](https://user-images.githubusercontent.com/8958987/224327964-0618b5c1-bcef-41b2-b7f8-77b3c2092dd2.png)

**Comment by stefcameron** [comment]
Try writing your tabbable mock module using CJS syntax instead of ESM. I think that will fix the issue.

**Comment by stefcameron** [comment]
i.e. `module.exports = tabbable;` instead of `export default tabbable`

Remember: Jest requires CJS. It doesn't natively understand ESM.

**Comment by neeco90** [comment]
Thanks a lot @stefcameron ! u was right! I left the final code for others who find something similar
![image](https://user-images.githubusercontent.com/8958987/224707779-956e2d6e-a65d-4554-beec-e27715e265f5.png)

**Comment by stefcameron** [comment]
You're welcome! I'm glad I could help! 🚀
